## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import ns3waf

def configure(conf):
    ns3waf.check_modules(conf, ['core', 'internet', 'point-to-point', 'lte', 'mmwave'], mandatory = True)

def build(bld):
    bld.build_a_script('dce', needed = ['core', 'internet', 'dce', 'point-to-point', 'lte', 'mmwave'],
				  target='bin/first-scenario',
				  source=['first-scenario.cc'],
				  )

